### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by neoeno**
I started looking into a few refactors but I decided probably best not to interfere too much!

The commits below contain additional information in the commit messages. You'll be able to see that if you click them.

### CODE REVIEW

**Comment by catquarks** [comment]
Thanks Caden! I shall do those things!

What kinds of refactors did you have in mind? I may do a completely new version in the future that's more 'inclusive' with regards to spouse genders; so at that point, I may as well do a complete overhaul on the code anyway.

I'll see what I can do about the heart. My text editor (leafpad) won't let me make tabs into groups of spaces. I downloaded 'gedit', but this little netbook can't handle it and freezes up every time.

**Comment by neoeno** [comment]
Well I started to extract this:

``` python
def print_and_wait(*messages):
  for message in messages:
    print message
    raw_input(">> ")
```

Because there's a lot of `print something, wait for an enter key`. But you could also extract the 'business logic' to a class or something, which would make your validation a little clearer. Those are just ideas though!

**Comment by neoeno** [comment]
Also if you can't run gedit you really do have a problem...!

**Comment by catquarks** [comment]
The heart is very special now! I just did all the spaces manually.

Except for in the last formatter, I kept getting errors like this whenever I changed the number formatters to %g:

Traceback (most recent call last):
  File "number_marriage_1-2.py", line 79, in <module>
    cancellation2(bride, groom)
  File "number_marriage_1-2.py", line 32, in cancellation2
    """ % (wrong, bad)
TypeError: float argument required, not str

I left them as %s because they actually look pretty friendly to me -- no quotes, no extra decimal places. But there is one %g at the end that worked normally: it looks normal and doesn't cause any errors.

Yup it's true, my keyboard spazzes out when I start typing into gedit for more than a few minutes. Very surprised I still manage to get things done on this thing...

Never thought about 'business logic' that way before!

**Comment by neoeno** [comment]
:+1: 

Yep — that's why this code only changes the last one too! Ha. There is a good reason why it breaks someplaces and doesn't others. `%g` formats numbers, so:

``` python
"Hello, %s!" % "World"        # => "Hello, World!"
"Hello, %g!" % "World"        # => TypeErr: float argument required, not str
"Hello, %g!" % 4                  # => "Hello, 4!"
```

But `raw_input` returns a string, so when you write:

``` python
groom = raw_input("[please enter another number]: ")
```

even though `groom` might look like a number, it's actually a string:

``` python
type(groom)    # => "<type 'str'>"
```

You've actually dealt with types already, in here:

``` python
def holy_matrimony(bride, groom):
    wife = float(bride)
    husband = float(groom)
    return wife + husband
```

You needed to convert `bride` to a `float` to get addition to work as you expected.

**Comment by neoeno** [comment]
(Also 'spaz' is a pretty fucked word.)

**Pull request closed without merging**
